### ISSUE TITLE
Remove build files from repo

### ISSUE THREAD

**Issue by viki53** [Qowala/Qowala-web-client#1]
I'm not sure the `build` folder should be pushed to the repo: as it is generated, it should only be local, hence ignored from the Git sync process.

Just putting the thought out there 😄

**Comment by KillianKemps** [comment]
The `build` folder is not generated 😃 
It contains all necessary configuration files for Webpack to build. The folder you mean is the `dist` folder which contains the minimized HTML and CSS after you do a `npm build`

All the Webpack configuration files have been generated with the `vue-cli` according to the `webpack` template: https://github.com/vuejs-templates/webpack

**Comment by viki53** [comment]
Ah, well, my bad!  😸
